"""Initial create lookup_data & search_log

Revision ID: 40abe5ed65ba
Revises: bb404c9bc7b8
Create Date: 2025-08-04 10:04:12.149375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40abe5ed65ba'
down_revision: Union[str, Sequence[str], None] = 'bb404c9bc7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_log')
    op.drop_table('lookup_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_data',
    sa.Column('entry', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detection_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('associated_ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entry', name=op.f('lookup_data_pkey'))
    )
    op.create_table('search_log',
    sa.Column('entry', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_searched', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_searched', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('lookup_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('entry', 'client_name', name=op.f('pk_search_log'))
    )
    # ### end Alembic commands ###
