"""Add ASN and detection_count columns

Revision ID: 531dc4008abe
Revises: 
Create Date: 2025-08-03 09:46:40.193922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531dc4008abe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry', sa.VARCHAR(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(), nullable=True),
    sa.Column('lookup_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_logs_id'), 'lookup_logs', ['id'], unique=False)
    # ### end Alembic commands ###
