"""Add created_at column to lookup_data

Revision ID: 8e75f52597be
Revises: 07414ab575fa
Create Date: 2025-08-06 10:07:47.904325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e75f52597be'
down_revision: Union[str, Sequence[str], None] = '07414ab575fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_data', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lookup_data', 'created_at')
    # ### end Alembic commands ###
