"""Add onupdate to last_updated

Revision ID: bb404c9bc7b8
Revises: e95646fb8da9
Create Date: 2025-08-03 10:11:56.339918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb404c9bc7b8'
down_revision: Union[str, Sequence[str], None] = 'e95646fb8da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
from sqlalchemy import text

def upgrade():
    conn = op.get_bind()
    index_check = conn.execute(
        text("SELECT to_regclass('public.ix_lookup_logs_id')")
    ).scalar()

    if index_check is not None:
        op.drop_index(op.f('ix_lookup_logs_id'), table_name='lookup_logs')

    # Your other upgrade commands...



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry', sa.VARCHAR(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(), nullable=False),
    sa.Column('isp', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('asn', sa.VARCHAR(), nullable=True),
    sa.Column('associated_ip', sa.VARCHAR(), nullable=True),
    sa.Column('detection_count', sa.INTEGER(), nullable=True),
    sa.Column('lookup_count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry')
    )
    op.create_index(op.f('ix_lookup_logs_id'), 'lookup_logs', ['id'], unique=False)
    # ### end Alembic commands ###
